stages:
  - compile
  - test

image:
    name: centos

.compile:
  stage: compile
  artifacts:
    paths:
      -  ci-test-output/
  only:
    variables:
      - $TEST_JOB =~ /\b(full|docker_test|rg)\b/i

compile_debug:
  script:
    - mkdir ci-test-output/
    -  echo "dubug" >  install.rpm
    -  echo "dubug.sh" > install.sh
    - mv install*  ci-test-output/
  extends:
    - .compile

compile_OEM:
  script:
    - mkdir ci-test-output/
    - echo "OEM" > install.rpm
    - echo "OEM.sh" >  install.sh
    - mv install*  ci-test-output/
  extends:
    - .compile


docker_test:
  image: centos:ssh_docker
  stage: test
  dependencies: [ "compile_OEM" ]
  script:
    - ssh 172.17.0.2
    - echo $(ifconfig)
  only:
    variables:
      - $TEST_JOB =~ /\b(full|docker_test)\b/i

regress_test:
  stage: test
  dependencies: [ "compile_debug" ]
  script:
    - ifconfig
  only:
    variables:
      - $TEST_JOB =~ /\b(full|rg)\b/i

